Processing updates
legend-exp/LegendDataManagement.jl pull request #22
Opened 2024-01-12 18:09 UTC by theHenks

Added functionality which was so far in the dataflow:

- `is_analysis_run` checks if the run is a analysis run
- `start_key` returns the starting FileKey for a given period and run
- `phy_livetime` returns the livetime for a given run and period

Also, I extended the `channelinfo` to be able to get the info for a given run and period by using the `start_key` as a reference and also to get a handy access to the `:geds` subsytem with 
``` julia
channelinfo(l200, (:p03, :r000, :cal))
channelinfo(l200, (:p03, :r000, :cal); system=:geds, processable=true)
```
This makes this whole process of getting filekeys etc way more handy and the user can just get the `channelinfo` for a given run much more human readable.

I will also move some of the `addprocs` functionality and try to start with some of the logging stuff. 
Maybe @oschulz, you could also share some ideas here. The missing features are here a way to first create Markdown logs and then write them. 
Then, a function `savelegendfig` would be nice which automatically generates figure names and saves a given figure.
And the option to save units in the `PropDicts` as discussed.

2024-01-25 11:01 UTC, oschulz commented on src/dataprod_config.jl
> +"""
Let's do

```julia
(period, run) in analysis_runs(data::LegendData)
```

instead.

2024-01-25 11:07 UTC, oschulz commented on src/dataprod_config.jl
> +function _get_runinfo(data::LegendData, period::DataPeriodLike, run::DataRunLike, category::DataCategoryLike, key::Symbol)
Let's have an exported function

```
runinfo(data::LegendData)::StructArray
```

instead, similar to `channelinfo`.

2024-01-25 11:12 UTC, oschulz commented on src/dataprod_config.jl
> +function start_filekey(data::LegendData, period::DataPeriodLike, run::DataRunLike, category::DataCategoryLike)
Should use `runinfo(data, period, run)` internally.

2024-01-25 11:22 UTC, oschulz requested changes

2024-01-25 11:22 UTC, oschulz commented on src/dataprod_config.jl
> +"""
This can just become

```
runinfo(data, perior, category).startkey
```

2024-01-25 14:02 UTC, theHenks commented on src/dataprod_config.jl
> +"""
Fixed but returned a StructArray instead to make it simnilar to the data_partitions. Also ok?

2024-01-25 14:02 UTC, theHenks commented on src/dataprod_config.jl
> +"""
```suggestion
function analysis_runs(data::LegendData)
    aruns = pydataprod_config(data).analysis_runs
    periods_and_runs = [
        let period = DataPeriod(string(p))
            map(run -> (period = period, run = run), _resolve_partition_runs(data, period, rs))
        end
        for (p,rs) in aruns
    ]
    flat_pr = vcat(periods_and_runs...)::Vector{@NamedTuple{period::DataPeriod, run::DataRun}}
    StructArray(flat_pr)
end
export analysis_runs
```

2024-01-25 14:30 UTC, theHenks commented on src/dataprod_config.jl
> +function _get_runinfo(data::LegendData, period::DataPeriodLike, run::DataRunLike, category::DataCategoryLike, key::Symbol)
Here my suggestion: 


```suggestion
function runinfo(data::LegendData, runsel::RunCategorySelLike)::NamedTuple
    # unpack runsel
    period, run, category = runsel
    period, run = DataPeriod(period), DataRun(run)
    # check if run, period and category is available
    if !haskey(data.metadata.dataprod.runinfo, Symbol(period))
        throw(ArgumentError("Invalid period $period"))
    elseif !haskey(data.metadata.dataprod.runinfo[Symbol(period)], Symbol(run))
        throw(ArgumentError("Invalid run $run in period $period"))
    elseif !haskey(data.metadata.dataprod.runinfo[Symbol(period)][Symbol(run)], Symbol(category))
        throw(ArgumentError("Invalid category $category in period $period and run $run"))
    end
    (
        startkey = FileKey(data.name, period, run, category, Timestamp(data.metadata.dataprod.runinfo[Symbol(period)][Symbol(run)][Symbol(category)][:start_key])), 
        livetime =  if haskey(data.metadata.dataprod.runinfo[Symbol(period)][Symbol(run)][Symbol(category)], :livetime_in_s)
                        Unitful.Quantity(data.metadata.dataprod.runinfo[Symbol(period)][Symbol(run)][Symbol(category)][:livetime_in_s], u"s") 
                    else 
                        Unitful.Quantity(NaN, u"s")
                    end
    )
end
export runinfo
```

2024-01-25 15:01 UTC, oschulz commented on src/legend_data.jl
>      channelinfo(data::LegendData, sel::AnyValiditySelection)
Let's do

```julia
channelinfo(data::LegendData, sel::AnyValiditySelection; system::Symbol = :all, only_processable::Bool = false)
channelinfo(data::LegendData, sel::RunSelLike; system::Symbol = :all, only_processable::Bool = false)
```

2024-01-25 21:11 UTC, theHenks commented
Ready to merge now from my side. What do you say @oschulz ?

2024-01-26 08:57 UTC, merged

2024-01-26 08:57 UTC, oschulz commented
Thanks!